// @ts-check
/**
 * tools/securitizationData/generate.js
 * Offline seeded generator for the demo securitization pool (Phase 5).
 * Emits ~1,000 micro-loans totalling ~RM5,000,000 and writes src/data/samplePool.ts.
 *
 * Run:  node tools/securitizationData/generate.js
 *
 * Each row is a PoolLoan (see src/lib/securitization.ts):
 *   { id, principal, apr, tenorMonths, score, band, fraudProb }
 *
 * The pool models credit-invisible micro-entrepreneurs: mostly Fair/Good with a
 * Building tail and fewer Strong/Excellent, RM2k-20k working capital, and a low
 * fraud-probability distribution with a small elevated tail. Deterministic: a fixed
 * seed means regenerating reproduces the exact same pool.
 */

'use strict';
const fs = require('fs');
const path = require('path');

// ── Seeded PRNG (xorshift32)  reproducible runs ────────────────────────────────
let _seed = 1337;
function rand() {
  _seed ^= _seed << 13;
  _seed ^= _seed >> 17;
  _seed ^= _seed << 5;
  return (_seed >>> 0) / 4294967296;
}
function randInt(lo, hi) {
  return Math.floor(rand() * (hi - lo + 1)) + lo;
}

const clamp = (x, lo, hi) => Math.max(lo, Math.min(hi, x));

// ── Pool shape ──────────────────────────────────────────────────────────────────
const N = 1000;

// Band mix (sums to 1) + score range per band (matches bandFor() in creditScore.ts).
const BANDS = [
  { band: 'Building', weight: 0.10, scoreLo: 380, scoreHi: 499 },
  { band: 'Fair', weight: 0.25, scoreLo: 500, scoreHi: 619 },
  { band: 'Good', weight: 0.35, scoreLo: 620, scoreHi: 739 },
  { band: 'Strong', weight: 0.22, scoreLo: 740, scoreHi: 819 },
  { band: 'Excellent', weight: 0.08, scoreLo: 820, scoreHi: 900 },
];

// Loan terms per band (from the DEFAULT_PRODUCTS ladder in loans.ts).
const TERMS = {
  Building: { apr: 0.28, tenorMonths: 12 },
  Fair: { apr: 0.28, tenorMonths: 12 },
  Good: { apr: 0.22, tenorMonths: 18 },
  Strong: { apr: 0.16, tenorMonths: 24 },
  Excellent: { apr: 0.16, tenorMonths: 24 },
};

function pickBand() {
  const r = rand();
  let acc = 0;
  for (const b of BANDS) {
    acc += b.weight;
    if (r <= acc) return b;
  }
  return BANDS[BANDS.length - 1];
}

/** Principal skewed toward smaller tickets (RM2k-20k working capital). */
function pickPrincipal() {
  // Square the uniform to bias low, then map into the range and round to RM50.
  const u = rand() * rand();
  const raw = 2000 + u * (20000 - 2000);
  return Math.round(raw / 50) * 50;
}

/** Mostly-clean fraud probability with a small elevated tail. */
function pickFraudProb(band) {
  const tail = rand() < 0.08; // ~8% of loans carry an elevated signal
  if (tail) return Math.round(clamp(0.2 + rand() * 0.4, 0, 1) * 100) / 100;
  const base = band === 'Building' ? 0.06 : 0.03;
  return Math.round(clamp(rand() * base, 0, 1) * 100) / 100;
}

// ── Generate ────────────────────────────────────────────────────────────────────
const loans = [];
for (let i = 0; i < N; i++) {
  const b = pickBand();
  const score = randInt(b.scoreLo, b.scoreHi);
  const terms = TERMS[b.band];
  loans.push({
    id: `L${String(i + 1).padStart(4, '0')}`,
    principal: pickPrincipal(),
    apr: terms.apr,
    tenorMonths: terms.tenorMonths,
    score,
    band: b.band,
    fraudProb: pickFraudProb(b.band),
  });
}

const totalPrincipal = loans.reduce((s, l) => s + l.principal, 0);

// ── Emit src/data/samplePool.ts ─────────────────────────────────────────────────
const header = `// AUTO-GENERATED by tools/securitizationData/generate.js (seed 1337). Do not edit by hand.
// Regenerate with: node tools/securitizationData/generate.js
// Pool: ${N} micro-loans, total principal RM${totalPrincipal.toLocaleString('en-MY')}.
import type { PoolLoan } from '../lib/securitization';

export const SAMPLE_POOL: PoolLoan[] = ${JSON.stringify(loans, null, 2)};
`;

const outPath = path.join(__dirname, '..', '..', 'src', 'data', 'samplePool.ts');
fs.writeFileSync(outPath, header);
console.log(`Wrote ${loans.length} loans (RM${totalPrincipal.toLocaleString('en-MY')}) → ${outPath}`);
