// Regenerates src/data/sampleStatements.ts from the captured demo-kit PNGs in assets/demo/.
// Embedding the PNGs as base64 constants keeps the tour's sample picker dependency-free: no
// expo-asset, no async asset resolution, identical on web and native. Re-run after
// re-capturing any PNG (see tools/demoKit/README.md for the capture step):
//   node tools/demoKit/emitSampleStatement.js
const fs = require('fs');
const path = require('path');

// id → { file, label, provider } for every statement offered in the tour's sample picker.
// Genuine, varied statements so the judge has a real choice; each carries full-year dates so
// vision extraction can't misdate the rows into a past year.
const SAMPLES = [
  { id: 'tng', file: 'kit1-tng.png', label: "Touch 'n Go eWallet", provider: 'E-wallet · spending' },
  { id: 'mae', file: 'kit2-mae.png', label: 'Maybank MAE', provider: 'Bank · income + bills' },
  { id: 'grab', file: 'kit3-grab.png', label: 'Grab driver payouts', provider: 'Gig income only' },
];

const assetsDir = path.join(__dirname, '..', '..', 'assets', 'demo');
const out = path.join(__dirname, '..', '..', 'src', 'data', 'sampleStatements.ts');

const entries = SAMPLES.map((s) => {
  const b64 = fs.readFileSync(path.join(assetsDir, s.file)).toString('base64');
  return { ...s, b64 };
});

const body = `// GENERATED by tools/demoKit/emitSampleStatement.js from the PNGs in assets/demo/.
// Do not edit by hand; re-capture the PNGs and re-run the generator instead. The tour's scan
// mission offers these as one-tap samples ALONGSIDE the judge's own upload  the app never
// injects an image on its own. Embedded as base64 so the picker needs no asset plumbing and
// no new dependency.
import type { PickedImage } from '../screens/AttachScreen';

export interface SampleStatement {
  id: string;
  label: string;
  /** Short provenance line shown under the label in the picker. */
  provider: string;
  image: PickedImage;
}

export const SAMPLE_STATEMENTS: SampleStatement[] = [
${entries
  .map(
    (e) => `  {
    id: '${e.id}',
    label: ${JSON.stringify(e.label)},
    provider: ${JSON.stringify(e.provider)},
    image: { uri: 'data:image/png;base64,${e.b64}', base64: '${e.b64}', mime: 'image/png' },
  },`
  )
  .join('\n')}
];
`;

fs.writeFileSync(out, body);
const kb = Math.round(body.length / 1024);
console.log(`Wrote ${out} (${entries.length} samples, ${kb} KB)`);
