// tools/issuerKey/from-env.js
// Materializes src/data/issuerKey.ts from ISSUER_PUBLIC_KEY / ISSUER_SECRET_KEY
// env vars. src/data/issuerKey.ts is gitignored (it held a leaked key before a
// rotation), so CI/Vercel builds have no local copy to import from source.mjs
// generate.js at build time; this script rehydrates the SAME pinned keypair
// instead, which LenderConsole's ISSUER_PUBLIC_KEY_HEX must keep matching.
//
// Run: node tools/issuerKey/from-env.js   (wired into vercel.json buildCommand)
'use strict';
const path = require('path');
const fs = require('fs');

const publicHex = process.env.ISSUER_PUBLIC_KEY;
const secretHex = process.env.ISSUER_SECRET_KEY;

if (!publicHex || !secretHex) {
  console.error(
    'issuerKey/from-env: ISSUER_PUBLIC_KEY / ISSUER_SECRET_KEY are not set. ' +
      'Set them in the Vercel project (Production + Preview) or run tools/issuerKey/generate.js locally.',
  );
  process.exit(1);
}

const out = path.join(__dirname, '../../src/data/issuerKey.ts');
const ts = `// AUTO-GENERATED by tools/issuerKey/from-env.js from ISSUER_PUBLIC_KEY / ISSUER_SECRET_KEY env vars  do not edit by hand.
// Pip issuer Ed25519 keypair. The lender console pins ISSUER_PUBLIC_KEY; the borrower
// app issuer-signs passports with ISSUER_SECRET_KEY. Bundling the secret is a DEMO
// simplification  production moves issuer signing to a server / device attestation.
export const ISSUER_PUBLIC_KEY = '${publicHex}';
export const ISSUER_SECRET_KEY = '${secretHex}';
`;
fs.writeFileSync(out, ts);
console.log('Wrote', out, 'from env vars');
console.log('issuer pubkey:', publicHex.slice(0, 16) + '…');
