// tools/issuerKey/generate.js
// One-time offline script — generates the Pip *issuer* Ed25519 keypair and writes
// src/data/issuerKey.ts. The lender console pins ISSUER_PUBLIC_KEY; the borrower app
// signs each passport with ISSUER_SECRET_KEY so a self-minted passport (no issuer
// secret) fails verification.
//
// DEMO LIMITATION (state this in the pitch): bundling the issuer secret on-device is a
// demo simplification. In production the issuer signature is produced by a server /
// device-attestation service that never ships the secret to clients.
//
// Run: node tools/issuerKey/generate.js   (already run; re-run only to rotate the key —
// you must then regenerate the sample passport: node tools/demoPassport/generate.js)

'use strict';
const path = require('path');
const fs = require('fs');
const ed = require('@noble/ed25519');
const { sha512 } = require(path.join(__dirname, '../../node_modules/@noble/hashes/sha2.js'));
ed.hashes.sha512 = sha512;

const secret = ed.utils.randomSecretKey();
const secretHex = Buffer.from(secret).toString('hex');
const publicHex = Buffer.from(ed.getPublicKey(secret)).toString('hex');

const out = path.join(__dirname, '../../src/data/issuerKey.ts');
const ts = `// AUTO-GENERATED by tools/issuerKey/generate.js — do not edit by hand.
// Pip issuer Ed25519 keypair. The lender console pins ISSUER_PUBLIC_KEY; the borrower
// app issuer-signs passports with ISSUER_SECRET_KEY. Bundling the secret is a DEMO
// simplification — production moves issuer signing to a server / device attestation.
export const ISSUER_PUBLIC_KEY = '${publicHex}';
export const ISSUER_SECRET_KEY = '${secretHex}';
`;
fs.writeFileSync(out, ts);
console.log('Wrote', out);
console.log('issuer pubkey:', publicHex.slice(0, 16) + '…');
