/**
 * tools/demoPassport/generate.js
 * One-time offline script — generates a pre-signed sample Credit Passport (holder +
 * issuer signatures, with the lender assessment block) and writes it to
 * src/data/samplePassport.ts.
 *
 * Run: node tools/demoPassport/generate.js
 * (Re-run after rotating the issuer key via tools/issuerKey/generate.js.)
 */

'use strict';

const path = require('path');
const fs = require('fs');
const ed = require('@noble/ed25519');
const { sha512 } = require(path.join(__dirname, '../../node_modules/@noble/hashes/sha2.js'));
ed.hashes.sha512 = sha512;

// ── Read the bundled issuer secret from src/data/issuerKey.ts ──────────────────
const issuerKeyTs = fs.readFileSync(path.join(__dirname, '../../src/data/issuerKey.ts'), 'utf8');
const secretMatch = issuerKeyTs.match(/ISSUER_SECRET_KEY\s*=\s*'([0-9a-f]+)'/);
if (!secretMatch) {
  console.error('Could not read ISSUER_SECRET_KEY — run tools/issuerKey/generate.js first.');
  process.exit(1);
}
const issuerSecret = Buffer.from(secretMatch[1], 'hex');

// ── 1. Holder keypair (the borrower) ───────────────────────────────────────────
const privKey = ed.utils.randomSecretKey();
const pubKeyHex = Buffer.from(ed.getPublicKey(privKey)).toString('hex');

// ── 2. Sample passport (672 / Good, coherent with the live demo profile) ───────
const issuedAt = '2026-06-09T08:00:00.000Z';
const validUntil = '2026-07-09T08:00:00.000Z';

const passport = {
  subject: pubKeyHex,
  score: 672,
  band: 'Good',
  factorSummary: [
    { key: 'cashflow',     subScore: 72 },
    { key: 'income',       subScore: 65 },
    { key: 'savings',      subScore: 55 },
    { key: 'debt',         subScore: 88 },
    { key: 'discipline',   subScore: 70 },
    { key: 'networth',     subScore: 52 },
    { key: 'track_record', subScore: 40 },
  ],
  provenanceSummary:
    'source trust 70%; Benford conformity 83%; 2% round amounts; 0% duplicates; coverage 70% of last 90 days; expenses 82% of income',
  evidenceHash:
    'abc123def456abc123def456abc123def456abc123def456abc123def456ab12',
  repaymentRecord: { onTime: 0, total: 0 },
  issuedAt,
  validUntil,
  assessment: {
    confidence: 0.62,
    coverageRatio: 0.7,
    coverageDays: 90,
    avgIncome: 2540,
    avgMonthlySurplus: 520,
    monthlyDebtService: 120,
  },
  holder: {
    name: 'Aisyah binti Rahman',
    nricMasked: '••••••-••-5678',
    verified: true,
    provider: 'Demo verification (mock)',
  },
};

// ── 3. Canonicalize (mirrors passport.ts) ──────────────────────────────────────
function sortKeys(obj) {
  if (Array.isArray(obj)) return obj.map(sortKeys);
  if (obj && typeof obj === 'object') {
    return Object.fromEntries(Object.keys(obj).sort().map((k) => [k, sortKeys(obj[k])]));
  }
  return obj;
}
const canonical = JSON.stringify(sortKeys(passport));
const msg = Buffer.from(canonical);

// ── 4. Sign with holder + issuer keys ──────────────────────────────────────────
const signature = Buffer.from(ed.sign(msg, privKey)).toString('hex');
const issuerSignature = Buffer.from(ed.sign(msg, issuerSecret)).toString('hex');

// ── 5. Self-verify both before writing ─────────────────────────────────────────
const holderOk = ed.verify(Buffer.from(signature, 'hex'), msg, ed.getPublicKey(privKey));
const issuerOk = ed.verify(Buffer.from(issuerSignature, 'hex'), msg, ed.getPublicKey(issuerSecret));
if (!holderOk || !issuerOk) {
  console.error(`ERROR: self-verification failed (holder=${holderOk}, issuer=${issuerOk}).`);
  process.exit(1);
}
console.log(`Self-verification PASSED (holder + issuer). Score ${passport.score}/${passport.band}.`);

// ── 6. Write src/data/samplePassport.ts ────────────────────────────────────────
const passportCode = JSON.stringify({ passport, signature, issuerSignature });
const outFile = path.join(__dirname, '../../src/data/samplePassport.ts');
fs.writeFileSync(
  outFile,
  `// Auto-generated by tools/demoPassport/generate.js — do not edit manually.\nexport const SAMPLE_PASSPORT_CODE = ${JSON.stringify(passportCode)};\n`,
);
console.log('Written:', outFile);
