/**
 * Guards the shipped save chime itself, not the code that plays it: assets/sounds/saved.wav
 * is generated by tools/sfx/gen.js, and a generator bug once shipped a structurally valid
 * WAV containing nothing but zero samples — every decoder accepted it, and it played silence.
 * A header check alone would have passed. These read the audio.
 */
import { readFileSync } from 'fs';
import { join } from 'path';

const WAV = join(__dirname, '..', 'assets', 'sounds', 'saved.wav');
const HEADER_BYTES = 44;
const FULL_SCALE = 32767;

const wav = readFileSync(WAV);

/** Decodes the mono 16-bit PCM payload to floats in -1..1. */
function samples(): number[] {
  const out: number[] = [];
  for (let i = HEADER_BYTES; i + 1 < wav.length; i += 2) out.push(wav.readInt16LE(i) / FULL_SCALE);
  return out;
}

describe('saved.wav header', () => {
  it('is mono 16-bit PCM at 44.1kHz, the format every mobile decoder handles natively', () => {
    expect(wav.toString('ascii', 0, 4)).toBe('RIFF');
    expect(wav.toString('ascii', 8, 12)).toBe('WAVE');
    expect(wav.readUInt16LE(20)).toBe(1); // PCM, uncompressed
    expect(wav.readUInt16LE(22)).toBe(1); // channels
    expect(wav.readUInt32LE(24)).toBe(44100);
    expect(wav.readUInt16LE(34)).toBe(16);
  });

  it('declares a data length matching the bytes actually present', () => {
    expect(wav.readUInt32LE(40)).toBe(wav.length - HEADER_BYTES);
  });
});

describe('saved.wav audio', () => {
  it('is audible — the defect that shipped was a valid header over pure silence', () => {
    const audible = samples().filter((s) => Math.abs(s) > 0.01);
    expect(audible.length).toBeGreaterThan(1000);
  });

  it('is loud enough to hear over a phone speaker without clipping', () => {
    const peak = samples().reduce((m, s) => Math.max(m, Math.abs(s)), 0);
    expect(peak).toBeGreaterThan(0.5);
    expect(peak).toBeLessThan(1);
  });

  it('opens and closes on silence, so neither end clicks', () => {
    const s = samples();
    expect(Math.abs(s[0])).toBeLessThan(0.01);
    expect(Math.abs(s[s.length - 1])).toBeLessThan(0.01);
  });

  it('carries both notes: audible energy in the second half, not just an opening blip', () => {
    const s = samples();
    const secondHalf = s.slice(Math.floor(s.length / 2));
    const peak = secondHalf.reduce((m, v) => Math.max(m, Math.abs(v)), 0);
    expect(peak).toBeGreaterThan(0.05);
  });

  it('stays short enough to read as a confirmation rather than a jingle', () => {
    const seconds = (wav.length - HEADER_BYTES) / 2 / 44100;
    expect(seconds).toBeGreaterThan(0.2);
    expect(seconds).toBeLessThan(1);
  });
});
