// AUTO-GENERATED by tools/issuerKey/generate.js — do not edit by hand.
// Pip issuer Ed25519 keypair. The lender console pins ISSUER_PUBLIC_KEY; the borrower
// app issuer-signs passports with ISSUER_SECRET_KEY. Bundling the secret is a DEMO
// simplification — production moves issuer signing to a server / device attestation.
export const ISSUER_PUBLIC_KEY = 'a120cfba5cc785efec44681cb59eb55bb41077c419c9afd7eaa9ba228150747b';
export const ISSUER_SECRET_KEY = '1eea1583a57efb0fd09f77645e34f71ad6ad258ead48819c358d110dc842806c';
